// de/app.html – the German twin of app.html, produced by phrase substitution so
// both stay in step. Add a pair here whenever app.html gains new copy.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const PAIRS = [
  ['<html lang="en">', '<html lang="de">'],
  ['<title>NotionKit Elements – App Preview</title>', '<title>NotionKit Elements – App-Vorschau</title>'],
  ['content="The NotionKit reference app built entirely from <nk-*> elements: sidebar, page tree, database, settings modal, command palette, AI thread and a live TipTap editor."', 'content="Die NotionKit-Referenz-App, vollständig aus <nk-*>-Elementen: Sidebar, Seitenbaum, Datenbank, Einstellungs-Modal, Befehlspalette, KI-Thread und ein Live-TipTap-Editor."'],
  ['content="NotionKit Elements – App Preview"', 'content="NotionKit Elements – App-Vorschau"'],
  ['content="The NotionKit reference app built entirely from <nk-*> elements."', 'content="Die NotionKit-Referenz-App, vollständig aus <nk-*>-Elementen."'],
  ['href="favicon.svg"', 'href="../favicon.svg"'], ['href="favicon.png"', 'href="../favicon.png"'], ['href="apple-touch-icon.png"', 'href="../apple-touch-icon.png"'],
  ['src="dist/notionkit-elements.min.js"', 'src="../dist/notionkit-elements.min.js"'], ['src="docs-editor.js"', 'src="../docs-editor.js"'],
  ['>Workspaces<', '>Arbeitsbereiche<'], ['>New workspace<', '>Neuer Workspace<'],
  ['no-actions>Search<', 'no-actions>Suche<'], ['value="home">Home<', 'value="home">Start<'], ['value="inbox">Inbox<', 'value="inbox">Eingang<'],
  ['addable>Favourites<', 'addable>Favoriten<'], ['value="overview" open>Project overview', 'value="overview" open>Projektübersicht'],
  ['value="kb">Knowledge base', 'value="kb">Wissensbasis'], ['value="design">Design system<', 'value="design">Designsystem<'], ['value="editorial">Editorial plan<', 'value="editorial">Redaktionsplan<'], ['value="clients">Client projects<', 'value="clients">Kundenprojekte<'],
  ['<nk-section-label>Team spaces</nk-section-label>', '<nk-section-label>Team-Bereiche</nk-section-label>'],
  ['no-actions>Settings<', 'no-actions>Einstellungen<'], ['no-actions>Trash<', 'no-actions>Papierkorb<'],
  ['<span>📊 Project overview</span>', '<span>📊 Projektübersicht</span>'], ['>Last edited 2 min ago<', '>Zuletzt bearbeitet vor 2 Min.<'], ['variant="share">Share<', 'variant="share">Teilen<'], ['title="Favourite"', 'title="Favorit"'],
  ['<span>📅 Created 12 May 2026</span>', '<span>📅 Erstellt am 12. Mai 2026</span>'], ['<nk-tag color="purple">Design system</nk-tag>', '<nk-tag color="purple">Designsystem</nk-tag>'],
  ['A calm UI framework in the Notion idiom – as web components, without a build step. This page is the living preview: sidebar, page tree, callouts, todos, toggles and database views in one shell.', 'Ein ruhiges UI-Framework im Notion-Stil – als Web Components, ohne Build-Schritt. Diese Seite ist die lebende Vorschau: Sidebar, Seitenbaum, Callouts, Todos, Toggles und Datenbank-Ansichten in einer Hülle.'],
  ['<strong>Core idea:</strong> NotionKit supplies the look and the shell; the editor is mounted through <em>&lt;nk-block-host&gt;</em> (BlockNote, say), and the data comes from your own API. Three layers, cleanly separated.', '<strong>Kernidee:</strong> NotionKit liefert Look und Hülle; der Editor wird über <em>&lt;nk-block-host&gt;</em> eingehängt (etwa BlockNote), die Daten kommen aus deiner eigenen API. Drei Schichten, sauber getrennt.'],
  ['<nk-heading>✅ Next steps</nk-heading>', '<nk-heading>✅ Nächste Schritte</nk-heading>'],
  ['<nk-todo checked>Sketch the component scope</nk-todo>', '<nk-todo checked>Komponentenumfang skizzieren</nk-todo>'], ['<nk-todo checked>Build the preview with light/dark</nk-todo>', '<nk-todo checked>Vorschau mit Hell/Dunkel bauen</nk-todo>'],
  ['<nk-todo>Prioritise the MVP scope</nk-todo>', '<nk-todo>MVP-Umfang priorisieren</nk-todo>'], ['<nk-todo>Define the data model for tree &amp; database</nk-todo>', '<nk-todo>Datenmodell für Baum &amp; Datenbank festlegen</nk-todo>'],
  ['<nk-heading>🗃️ Project database</nk-heading>', '<nk-heading>🗃️ Projektdatenbank</nk-heading>'], ['label="▦ Table"', 'label="▦ Tabelle"'],
  ['<nk-heading>🧩 More building blocks</nk-heading>', '<nk-heading>🧩 Weitere Bausteine</nk-heading>'],
  ['Everything else a Notion-like system needs – calm, drop-in elements. Try them out.', 'Alles, was ein Notion-artiges System sonst braucht – ruhige Drop-in-Elemente. Probier sie aus.'],
  ['This page is a <b>component preview</b> – every element follows the same design tokens.', 'Diese Seite ist eine <b>Komponenten-Vorschau</b> – jedes Element folgt denselben Design-Tokens.'], ['id="bannerCmdk">Open palette<', 'id="bannerCmdk">Palette öffnen<'],
  ['The “Project overview” database has 2 overdue entries.', 'Die Datenbank „Projektübersicht“ hat 2 überfällige Einträge.'], ['<span slot="action">View</span>', '<span slot="action">Ansehen</span>'], ['All changes have been synced.', 'Alle Änderungen wurden synchronisiert.'],
  ['<h4>Inline elements</h4>', '<h4>Inline-Elemente</h4>'],
  ['Running text can link', 'Fließtext kann'], ['Sara Lindt</nk-mention>,\n          pages such as', 'Sara Lindt</nk-mention> verlinken,\n          Seiten wie'], ['📄 Knowledge base</nk-mention> and dates such as', '📄 Wissensbasis</nk-mention> und Daten wie'], ['📅 20 May</nk-mention> – and just as easily', '📅 20. Mai</nk-mention> – und ebenso leicht'], ['</code> as code.', '</code> als Code.'],
  ['<h4>Emoji picker</h4>', '<h4>Emoji-Auswahl</h4>'], ['placeholder="Search emoji …"', 'placeholder="Emoji suchen …"'],
  ['<h4>Context menu (⋯)</h4>', '<h4>Kontextmenü (⋯)</h4>'], ['type="label">Page<', 'type="label">Seite<'], ['value="rename">Rename<', 'value="rename">Umbenennen<'], ['value="duplicate">Duplicate<', 'value="duplicate">Duplizieren<'], ['value="link">Copy link<', 'value="link">Link kopieren<'], ['value="move">Move to …<', 'value="move">Verschieben nach …<'], ['value="trash">Move to trash<', 'value="trash">In den Papierkorb<'],
  ['<h4>Page tabs</h4>', '<h4>Seiten-Tabs</h4>'], ['value="notes">📝 Notes<', 'value="notes">📝 Notizen<'], ['value="tasks">✅ Tasks<', 'value="tasks">✅ Aufgaben<'], ['value="files">📎 Files<', 'value="files">📎 Dateien<'],
  ['Free-form notes on the project – meeting minutes, ideas, rough drafts.', 'Freie Notizen zum Projekt – Protokolle, Ideen, Entwürfe.'], ['Tasks for this project, linked to the database below.', 'Aufgaben zu diesem Projekt, verknüpft mit der Datenbank oben.'], ['Attached files and exports.', 'Angehängte Dateien und Exporte.'],
  ['<h4>Template buttons</h4>', '<h4>Vorlagen-Buttons</h4>'], ['value="Week plan">Insert week plan<', 'value="Wochenplan">Wochenplan einfügen<'], ['value="Meeting minutes">Insert meeting minutes<', 'value="Meeting-Protokoll">Meeting-Protokoll einfügen<'], ['value="Retro board">Insert retro board<', 'value="Retro-Board">Retro-Board einfügen<'],
  ['<h4>Stat cards</h4>', '<h4>Kennzahl-Karten</h4>'], ['label="Active pages"', 'label="Aktive Seiten"'], ['delta="▲ 12 this week"', 'delta="▲ 12 diese Woche"'], ['label="AI requests"', 'label="KI-Anfragen"'], ['label="Open tasks"', 'label="Offene Aufgaben"'], ['delta="▼ 5 since yesterday"', 'delta="▼ 5 seit gestern"'],
  ['<h4>Synced block</h4>', '<h4>Synchronisierter Block</h4>'], ['badge="⟳ 3 places"', 'badge="⟳ 3 Orte"'], ['<b>Our mission:</b> Take real weight off the working day – calm, clear, effective. This text appears identically on three pages and is maintained in one place.', '<b>Unsere Mission:</b> Dem Arbeitstag echtes Gewicht nehmen – ruhig, klar, wirksam. Dieser Text erscheint identisch auf drei Seiten und wird an einer Stelle gepflegt.'],
  ['<h4>Segmented control</h4>', '<h4>Segment-Schalter</h4>'], ['value="week">Week<', 'value="week">Woche<'], ['value="month">Month<', 'value="month">Monat<'], ['value="quarter">Quarter<', 'value="quarter">Quartal<'], ['For time ranges, perspectives or density levels.', 'Für Zeiträume, Perspektiven oder Dichtestufen.'],
  ['<h4>Avatar group &amp; presence</h4>', '<h4>Avatar-Gruppe &amp; Präsenz</h4>'], ['5 people have access', '5 Personen haben Zugriff'],
  ['<h4>Loading skeleton</h4>', '<h4>Lade-Skelett</h4>'], ['<h4>Empty state</h4>', '<h4>Leerzustand</h4>'], ['title="No entries yet" desc="Create the first entry or import existing data."', 'title="Noch keine Einträge" desc="Lege den ersten Eintrag an oder importiere Daten."'], ['id="emptyNew">＋ New entry<', 'id="emptyNew">＋ Neuer Eintrag<'],
  ['<h4>Comment thread</h4>', '<h4>Kommentar-Faden</h4>'], ['placeholder="Comment …" send-label="Send"', 'placeholder="Kommentieren …" send-label="Senden"'], ['time="1 hr ago"', 'time="vor 1 Std."'], ['The board view already feels very close to the original. 👍', 'Die Board-Ansicht fühlt sich schon sehr nah am Original an. 👍'], ['time="20 min ago"', 'time="vor 20 Min."'], ['I have flagged the overdue entries and prepared a summary.', 'Ich habe die überfälligen Einträge markiert und eine Zusammenfassung vorbereitet.'],
  ['<h4>AI assistant embedding</h4>', '<h4>KI-Assistent eingebettet</h4>'], ['Summarise the open tasks for this project.', 'Fasse die offenen Aufgaben dieses Projekts zusammen.'],
  ['Two tasks are open: the <b>Table-View</b> sits at 65 % (due 20 May), the <b>Board with drag and drop</b> is planned. I would nail down the MVP scope first.', 'Zwei Aufgaben sind offen: die <b>Table-View</b> steht bei 65 % (fällig 20. Mai), das <b>Board mit Drag-and-Drop</b> ist geplant. Ich würde zuerst den MVP-Umfang festzurren.'],
  ['value="copy">📋 Copy<', 'value="copy">📋 Kopieren<'], ['value="rephrase">↻ Rephrase<', 'value="rephrase">↻ Umformulieren<'], ['placeholder="Ask Mona something …"', 'placeholder="Frag Mona etwas …"'],
  ['label="What does integrating it look like?"', 'label="Wie sieht die Integration aus?"'], ['One script tag is enough – no bundler, no framework lock-in:', 'Ein Script-Tag genügt – kein Bundler, kein Framework-Zwang:'], ['&lt;nk-page-title&gt;Project overview&lt;/nk-page-title&gt;', '&lt;nk-page-title&gt;Projektübersicht&lt;/nk-page-title&gt;'],
  ['label="What is deliberately not part of the kit?"', 'label="Was ist bewusst nicht Teil des Kits?"'], ['The text editor itself. With <em>&lt;nk-block-host&gt;</em> only the optical shell – TipTap, BlockNote or Novel is mounted as the editor. <em>&lt;nk-editor&gt;</em>, a thin TipTap wrapper, follows in v1.1.', 'Der Texteditor selbst. Mit <em>&lt;nk-block-host&gt;</em> nur die optische Hülle – TipTap, BlockNote oder Novel wird als Editor eingehängt. <em>&lt;nk-editor&gt;</em>, ein dünner TipTap-Wrapper, folgt in v1.1.'],
  ['<nk-heading>✍️ Editor surface</nk-heading>', '<nk-heading>✍️ Editorfläche</nk-heading>'], ['From here on you are typing into real <b>TipTap</b>, mounted into an <code class="nk-inline-code">nk-block-host</code> – with no editor CSS of its own. Hover a block for ＋ / ⠿, drag it, select text, or type <nk-kbd>/</nk-kbd>.', 'Ab hier tippst du in echtes <b>TipTap</b>, gemountet in einen <code class="nk-inline-code">nk-block-host</code> – ohne eigenes Editor-CSS. Fahre über einen Block für ＋ / ⠿, ziehe ihn, markiere Text oder tippe <nk-kbd>/</nk-kbd>.'],
  ['<p>This is no longer a preview: this paragraph is editable. The title above, the callout, the todos and the database are NotionKit elements – and this block is the same look, only alive.</p>', '<p>Das hier ist keine Vorschau mehr: Dieser Absatz ist editierbar. Der Titel oben, das Callout, die Todos und die Datenbank sind NotionKit-Elemente – und dieser Block ist derselbe Look, nur lebendig.</p>'],
  ['data-checked="true">Mount the editor into a block host</li>', 'data-checked="true">Editor in einen Block-Host mounten</li>'], ['data-checked="false">Move a block with ⠿</li>', 'data-checked="false">Einen Block mit ⠿ verschieben</li>'], ['data-checked="false">Pick a new block with <code>/</code></li>', 'data-checked="false">Mit <code>/</code> einen neuen Block wählen</li>'],
  ['<blockquote>NotionKit supplies the look and the shell, the editor supplies the behaviour. Three layers, cleanly separated.</blockquote>', '<blockquote>NotionKit liefert Look und Hülle, der Editor das Verhalten. Drei Schichten, sauber getrennt.</blockquote>'],
  // settings
  ['group="Account" icon="👤" label="My profile" title="My profile"', 'group="Konto" icon="👤" label="Mein Profil" title="Mein Profil"'], ['small>Upload image<', 'small>Bild hochladen<'], ['>Remove</nk-btn>', '>Entfernen</nk-btn>'], ['<h3>Details</h3>', '<h3>Details</h3>'],
  ['label="Display name" desc="How you appear in the workspace."', 'label="Anzeigename" desc="So erscheinst du im Workspace."'], ['label="E-Mail" desc="Used for invitations and notifications."', 'label="E-Mail" desc="Für Einladungen und Benachrichtigungen."'], ['label="About me" desc="A short description for your team."', 'label="Über mich" desc="Eine kurze Beschreibung für dein Team."'], ['placeholder="A few words about yourself …">Builds calm knowledge systems and AI-native ways of working.', 'placeholder="Ein paar Worte über dich …">Baut ruhige Wissenssysteme und KI-native Arbeitsweisen.'],
  ['data-save>Save changes<', 'data-save>Änderungen speichern<'], ['<nk-btn variant="secondary">Discard</nk-btn>', '<nk-btn variant="secondary">Verwerfen</nk-btn>'],
  ['group="Account" icon="🎨" label="Appearance" title="Appearance"', 'group="Konto" icon="🎨" label="Darstellung" title="Darstellung"'], ['label="Appearance" desc="Light, dark, or follow the system setting."', 'label="Darstellung" desc="Hell, dunkel oder der Systemeinstellung folgen."'], ['<option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option>', '<option value="light">Hell</option><option value="dark">Dunkel</option><option value="system">System</option>'],
  ['label="Palette" desc="The example palettes from theme-override.css – one line of --nk-accent on :root re-brands every element."', 'label="Palette" desc="Die Beispielpaletten aus theme-override.css – eine Zeile --nk-accent auf :root brandet jedes Element um."'], ['<option value="default">Default</option>', '<option value="default">Standard</option>'], ['<option value="high-contrast">High contrast</option>', '<option value="high-contrast">Hoher Kontrast</option>'],
  ['label="Language"><nk-select><option>German</option><option>English</option>', 'label="Sprache"><nk-select><option>Deutsch</option><option>Englisch</option>'], ['<h3>Comfort</h3>', '<h3>Komfort</h3>'], ['label="Compact view" desc="Reduces spacing in the sidebar and lists."', 'label="Kompakte Ansicht" desc="Weniger Abstand in Sidebar und Listen."'], ['label="Reduce motion" desc="Less motion for calmer work."', 'label="Bewegung reduzieren" desc="Weniger Animation für ruhigeres Arbeiten."'], ['label="Text size" desc="100 %"', 'label="Textgröße" desc="100 %"'],
  ['group="Account" icon="🔔" label="Notifications" title="Notifications"', 'group="Konto" icon="🔔" label="Benachrichtigungen" title="Benachrichtigungen"'], ['<h3>By email</h3>', '<h3>Per E-Mail</h3>'], ['<nk-check checked>Mentions and comments</nk-check>', '<nk-check checked>Erwähnungen und Kommentare</nk-check>'], ['<nk-check checked>Weekly digest</nk-check>', '<nk-check checked>Wöchentliche Zusammenfassung</nk-check>'], ['<nk-check>Product news</nk-check>', '<nk-check>Produktneuigkeiten</nk-check>'],
  ['label="Push notifications" desc="Straight in the browser when shared pages see activity."', 'label="Push-Benachrichtigungen" desc="Direkt im Browser, wenn sich auf geteilten Seiten etwas tut."'], ['label="Mentions only" desc="Everything else lands quietly in the inbox."', 'label="Nur Erwähnungen" desc="Alles andere landet leise im Eingang."'],
  ['group="Account" icon="✨" label="AI assistant" title="AI assistant"', 'group="Konto" icon="✨" label="KI-Assistent" title="KI-Assistent"'], ['label="AI replies enabled" desc="Mona may read page content and suggest replies."', 'label="KI-Antworten aktiv" desc="Mona darf Seiteninhalte lesen und Antworten vorschlagen."'], ['<h3>Model</h3>', '<h3>Modell</h3>'],
  ['desc="A balanced model for everyday work. Fast, calm, dependable." selected><span slot="title">Mona Standard <span class="nk-tag green">Recommended</span></span>', 'desc="Ein ausgewogenes Modell für den Alltag. Schnell, ruhig, verlässlich." selected><span slot="title">Mona Standard <span class="nk-tag green">Empfohlen</span></span>'],
  ['title="Mona Deep" desc="More depth of thought for complex analysis and long documents. Answers more slowly."', 'title="Mona Deep" desc="Mehr Denktiefe für komplexe Analysen und lange Dokumente. Antwortet langsamer."'], ['desc="Connect your own API key (OpenAI, Anthropic, Azure)."><span slot="title">Custom model', 'desc="Eigenen API-Schlüssel verbinden (OpenAI, Anthropic, Azure)."><span slot="title">Eigenes Modell'],
  ['<h3>Reply style</h3>', '<h3>Antwortstil</h3>'], ['checked>Calm &amp; concise<', 'checked>Ruhig &amp; knapp<'], ['value="detailed">Detailed &amp; explanatory<', 'value="detailed">Ausführlich &amp; erklärend<'], ['value="bullets">Bullet points only<', 'value="bullets">Nur Stichpunkte<'],
  ['label="API key" desc="Only needed for a custom model. Stays stored locally."', 'label="API-Schlüssel" desc="Nur für ein eigenes Modell nötig. Bleibt lokal gespeichert."'], ['data-save>Save</nk-btn>', 'data-save>Speichern</nk-btn>'], ['<nk-btn variant="secondary">Test connection</nk-btn>', '<nk-btn variant="secondary">Verbindung testen</nk-btn>'],
  ['group="Workspace" icon="⚙️" label="General" title="Workspace settings"', 'group="Workspace" icon="⚙️" label="Allgemein" title="Workspace-Einstellungen"'], ['label="Workspace name"', 'label="Workspace-Name"'], ['label="Domain" desc="Public pages appear under this address."', 'label="Domain" desc="Öffentliche Seiten erscheinen unter dieser Adresse."'], ['label="Public home page" desc="Visitors may view shared pages without signing in."', 'label="Öffentliche Startseite" desc="Besucher sehen geteilte Seiten ohne Anmeldung."'],
  ['title="⚠️ Danger zone"', 'title="⚠️ Gefahrenzone"'], ['label="Delete workspace" desc="Irreversibly removes all pages, databases and members."', 'label="Workspace löschen" desc="Entfernt unwiderruflich alle Seiten, Datenbanken und Mitglieder."'], ['data-save-danger>Delete<', 'data-save-danger>Löschen<'],
  ['group="Workspace" icon="👥" label="Members" title="Members"', 'group="Workspace" icon="👥" label="Mitglieder" title="Mitglieder"'], ['placeholder="Invite an email address …"', 'placeholder="E-Mail-Adresse einladen …"'], ['data-save>Invite<', 'data-save>Einladen<'], ['mail="Virtual co-founder"', 'mail="Virtuelle Mitgründerin"'],
  ['<option>Owner</option>', '<option>Eigentümer</option>'], ['<option>Admin</option><option>Member</option><option>Viewer</option>', '<option>Admin</option><option>Mitglied</option><option>Betrachter</option>'], ['<option>Member</option><option>Admin</option><option>Viewer</option>', '<option>Mitglied</option><option>Admin</option><option>Betrachter</option>'], ['<option>Full access</option><option>Restricted</option>', '<option>Voller Zugriff</option><option>Eingeschränkt</option>'],
  ['placeholder="Search or type a command …"', 'placeholder="Suchen oder Befehl eingeben …"'],
  // script strings
  ["{ value: 'planned', label: 'Planned', color: 'orange' }", "{ value: 'planned', label: 'Geplant', color: 'orange' }"], ["{ value: 'progress', label: 'In progress', color: 'blue' }", "{ value: 'progress', label: 'In Arbeit', color: 'blue' }"], ["{ value: 'done', label: 'Done', color: 'green' }", "{ value: 'done', label: 'Erledigt', color: 'green' }"],
  ["label: 'Owner', type: 'person'", "label: 'Verantwortlich', type: 'person'"], ["label: 'Due', type: 'date'", "label: 'Fällig', type: 'date'"], ["label: 'Progress', type: 'progress'", "label: 'Fortschritt', type: 'progress'"],
  ["name: 'Untitled ' + counter++", "name: 'Unbenannt ' + counter++"], ["toast.show('New page created')", "toast.show('Neue Seite angelegt')"], ["toast.show('Views: table and board – more in your app')", "toast.show('Ansichten: Tabelle und Board – mehr in deiner App')"], ["toast.show(`Sorted by ${e.detail.key} (${e.detail.value})`)", "toast.show(`Sortiert nach ${e.detail.key} (${e.detail.value})`)"],
  ["toast.show(`Open “${e.detail.row.name}”`)", "toast.show(`„${e.detail.row.name}“ öffnen`)"], ["toast.show(`${e.detail.action === 'add' ? 'Add page under' : 'Options for'} “${e.detail.label}”`)", "toast.show(`${e.detail.action === 'add' ? 'Seite anlegen unter' : 'Optionen für'} „${e.detail.label}“`)"], ["toast.show('Trash is empty')", "toast.show('Der Papierkorb ist leer')"], ["toast.show(`Workspace: ${e.detail.label}`)", "toast.show(`Workspace: ${e.detail.label}`)"],
  ["toast.show(e.detail.value === 'dark' ? 'Dark mode on' : 'Light mode on')", "toast.show(e.detail.value === 'dark' ? 'Dunkelmodus an' : 'Hellmodus an')"], ["toast.show('Following the system setting')", "toast.show('Folgt der Systemeinstellung')"], ["toast.show(`Palette: ${e.detail.value}`)", "toast.show(`Palette: ${e.detail.value}`)"],
  ["toast.show('Text size set to ' + e.detail.value + ' %')", "toast.show('Textgröße auf ' + e.detail.value + ' % gesetzt')"], ["toast.show('Settings saved')", "toast.show('Einstellungen gespeichert')"], ["toast.show('Just a preview – nothing was deleted')", "toast.show('Nur eine Vorschau – nichts wurde gelöscht')"],
  ["{ group: 'Pages', items: [", "{ group: 'Seiten', items: ["], ["label: 'Knowledge base' }", "label: 'Wissensbasis' }"], ["label: 'Editorial plan' }", "label: 'Redaktionsplan' }"], ["{ group: 'Actions', items: [", "{ group: 'Aktionen', items: ["], ["label: 'Create new page', shortcut", "label: 'Neue Seite anlegen', shortcut"], ["label: 'Toggle theme', shortcut", "label: 'Theme wechseln', shortcut"], ["label: 'Open settings', shortcut", "label: 'Einstellungen öffnen', shortcut"], ["label: 'Export page …' }", "label: 'Seite exportieren …' }"],
  ["toast.show(`Page icon set to ${e.detail.emoji}`)", "toast.show(`Seiten-Icon gesetzt: ${e.detail.emoji}`)"], ["toast.show('Pick an icon in the emoji picker below')", "toast.show('Wähle ein Icon in der Emoji-Auswahl unten')"], ["toast.show(`Menu: ${e.detail.label}`)", "toast.show(`Menü: ${e.detail.label}`)"], ["toast.show(`Template “${e.detail.value}” inserted`)", "toast.show(`Vorlage „${e.detail.value}“ eingefügt`)"], ["toast.show(`Range: ${e.detail.value}`)", "toast.show(`Zeitraum: ${e.detail.value}`)"], ["toast.show('New entry')", "toast.show('Neuer Eintrag')"],
  ["c.setAttribute('time', 'just now')", "c.setAttribute('time', 'gerade eben')"], ["toast.show('Comment sent')", "toast.show('Kommentar gesendet')"], ["toast.show(`AI: ${e.detail.action}`)", "toast.show(`KI: ${e.detail.action}`)"], ["toast.show('Mona is thinking …')", "toast.show('Mona denkt nach …')"], ["toast.show(`Renamed to “${e.detail.value}”`)", "toast.show(`Umbenannt in „${e.detail.value}“`)"],
];

let html = readFileSync('app.html', 'utf-8');
const missing = [];
for (const [en, de] of PAIRS) {
  if (!html.includes(en)) { missing.push(en); continue; }
  html = html.split(en).join(de);
}
if (missing.length) { console.error('❌ build-app-de: phrases not found in app.html:\n  ' + missing.join('\n  ')); process.exit(1); }
mkdirSync('de', { recursive: true });
writeFileSync('de/app.html', html);
console.log(`✅ de/app.html generated (${PAIRS.length} phrases)`);
