// Phrase dictionary used inside catalog examples, so the catalog itself stays
// language-neutral. Same idea as tools/words.mjs in the NotionKit foundation.
export const WORDS = {
  en: {
    save: 'Save', cancel: 'Cancel', delete: 'Delete', share: 'Share', newPage: 'New page',
    inProgress: 'In progress', done: 'Done', planned: 'Planned', design: 'Design',
    calloutText: 'A callout carries one thought that must not be missed.',
    displayName: 'Display name', displayNameDesc: 'Shown next to your comments.',
    email: 'Email', bio: 'Short bio', bioPlaceholder: 'A sentence about you',
    role: 'Role', viewer: 'Viewer', editor: 'Editor', admin: 'Admin',
    notify: 'Email notifications', weekly: 'Weekly digest', mentions: 'Mentions only',
    concise: 'Concise', balanced: 'Balanced', detailed: 'Detailed',
    fontSize: 'Font size', section: 'Section heading', details: 'Details',
    toggleBody: 'Folded content lives here.', todo1: 'Write the docs', todo2: 'Ship it',
    quote: 'The best interface is the one that gets out of the way.', quoteCite: 'Unknown',
    label: 'Label', open: 'Open', search: 'Search',
    workspace: 'MonaHilft', home: 'Home', inbox: 'Inbox', favourites: 'Favourites', workspaceSection: 'Workspace', teamSpaces: 'Team spaces',
    projectOverview: 'Project overview', mvp: 'NotionKit MVP', voh: 'Voice-Office-Hub', knowledgeBase: 'Knowledge base', onboarding: 'Onboarding', playbooks: 'Playbooks',
    designSystem: 'Design system', editorialPlan: 'Editorial plan', settings: 'Settings', trash: 'Trash', lastEdited: 'Last edited 2 min ago',
    switchWorkspace: 'Switch workspace', pageTitle: 'NotionKit MVP', lead: 'A calm, document-centric workspace app – built from elements only.',
    owner: '👤 Marcel Karas', created: '📅 Created 12 May 2026', tagged: '🏷️', bannerInfo: 'This page is a <b>component preview</b> – every element follows the same design tokens.', openPalette: 'Open palette',
    bannerWarn: 'The “Project overview” database has 2 overdue entries.', view: 'View', bannerOk: 'All changes have been synced.',
    emptyTitle: 'No entries yet', emptyDesc: 'Create the first entry or import existing data.', newEntry: '＋ New entry',
    syncedBadge: '⟳ 3 places', syncedText: '<b>Our mission:</b> Take real weight off the working day – calm, clear, effective.',
    notes: '📝 Notes', tasks: '✅ Tasks', files: '📎 Files', notesText: 'Free-form notes on the project – meeting minutes, ideas, rough drafts.', tasksText: 'Tasks for this project, linked to the database below.', filesText: 'Attached files and exports.',
    week: 'Week', month: 'Month', quarter: 'Quarter', activePages: 'Active pages', aiRequests: 'AI requests', openTasks: 'Open tasks', deltaPages: '▲ 12 this week', deltaAi: '▲ 23 %', deltaTasks: '▼ 5 since yesterday',
    people: '5 people have access', weekPlan: 'Insert week plan', minutes: 'Insert meeting minutes', retro: 'Insert retro board',
    modelPro: 'Mona Pro', modelProDesc: 'Best for long documents and research.', modelFast: 'Mona Fast', modelFastDesc: 'Quick answers, lower cost.', changePhoto: 'Change photo', remove: 'Remove',
    dangerTitle: 'Danger zone', dangerDesc: 'Deleting the workspace removes every page.', deleteWorkspace: 'Delete workspace', editableHint: 'Block content lives here – click to focus.',
    mentionPerson: 'Sara Lindt', mentionPage: '📄 Onboarding', mentionDate: '📅 20 May',
    account: 'Account', myProfile: 'My profile', appearance: 'Appearance', notifications: 'Notifications', aiAssistant: 'AI assistant', general: 'General', members: 'Members',
    userName: 'Marcel Karas', userMail: 'marcel@monahilft.de', theme: 'Theme', light: 'Light', dark: 'Dark', system: 'System', language: 'Language',
    rename: 'Rename', duplicate: 'Duplicate', moveTo: 'Move to …', page: 'Page', options: 'Options', searchCommand: 'Search or type a command …',
    pages: 'Pages', actions: 'Actions', newPageCmd: 'Create new page', toggleTheme: 'Toggle theme', openSettings: 'Open settings', exportPage: 'Export page …',
    dbName: 'Name', dbStatus: 'Status', dbOwner: 'Owner', dbDue: 'Due', dbProgress: 'Progress', table: '▦ Table', board: '▤ Board',
    p1: 'App shell & sidebar', p2: 'Page shell & typography', p3: 'Database table view', p4: 'Board view & drag-and-drop', statusDone: 'Done', statusProgress: 'In progress', statusPlanned: 'Planned',
    searchRows: 'Search rows …', filterDone: 'Status: Done', commentText1: 'The board view already feels very close to the original. 👍', commentText2: 'I have flagged the overdue entries and prepared a summary.', commentPlaceholder: 'Comment …', send: 'Send',
    you: 'You', aiName: 'Mona', aiBadge: '· AI', aiQuestion: 'Summarise the open tasks for this project.', aiAnswer: 'Two tasks are open: the <b>table view</b> sits at 65 % (due 20 May), the <b>board with drag and drop</b> is planned.', copy: '📋 Copy', rephrase: '↻ Rephrase', askAi: 'Ask Mona something …',
    toastText: 'Settings saved', showToast: 'Show toast', openModal: 'Open settings', openPalette2: 'Open palette (⌘K)', pickEmoji: 'Pick an icon', navigate: 'navigate', openHint: 'open', toggleHint: 'toggle',
  },
  de: {
    save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', share: 'Teilen', newPage: 'Neue Seite',
    inProgress: 'In Arbeit', done: 'Erledigt', planned: 'Geplant', design: 'Design',
    calloutText: 'Ein Callout trägt einen Gedanken, der nicht untergehen darf.',
    displayName: 'Anzeigename', displayNameDesc: 'Erscheint neben deinen Kommentaren.',
    email: 'E-Mail', bio: 'Kurzprofil', bioPlaceholder: 'Ein Satz über dich',
    role: 'Rolle', viewer: 'Betrachter', editor: 'Bearbeiter', admin: 'Admin',
    notify: 'E-Mail-Benachrichtigungen', weekly: 'Wöchentliche Zusammenfassung', mentions: 'Nur Erwähnungen',
    concise: 'Knapp', balanced: 'Ausgewogen', detailed: 'Ausführlich',
    fontSize: 'Schriftgröße', section: 'Abschnittsüberschrift', details: 'Details',
    toggleBody: 'Hier steht der eingeklappte Inhalt.', todo1: 'Doku schreiben', todo2: 'Ausliefern',
    quote: 'Die beste Oberfläche ist die, die aus dem Weg geht.', quoteCite: 'Unbekannt',
    label: 'Beschriftung', open: 'Öffnen', search: 'Suche',
    workspace: 'MonaHilft', home: 'Start', inbox: 'Eingang', favourites: 'Favoriten', workspaceSection: 'Workspace', teamSpaces: 'Team-Bereiche',
    projectOverview: 'Projektübersicht', mvp: 'NotionKit MVP', voh: 'Voice-Office-Hub', knowledgeBase: 'Wissensbasis', onboarding: 'Onboarding', playbooks: 'Playbooks',
    designSystem: 'Designsystem', editorialPlan: 'Redaktionsplan', settings: 'Einstellungen', trash: 'Papierkorb', lastEdited: 'Zuletzt bearbeitet vor 2 Min.',
    switchWorkspace: 'Workspace wechseln', pageTitle: 'NotionKit MVP', lead: 'Eine ruhige, dokumentzentrierte Workspace-App – nur aus Elementen gebaut.',
    owner: '👤 Marcel Karas', created: '📅 Erstellt am 12. Mai 2026', tagged: '🏷️', bannerInfo: 'Diese Seite ist eine <b>Komponenten-Vorschau</b> – jedes Element folgt denselben Design-Tokens.', openPalette: 'Palette öffnen',
    bannerWarn: 'Die Datenbank „Projektübersicht“ hat 2 überfällige Einträge.', view: 'Ansehen', bannerOk: 'Alle Änderungen wurden synchronisiert.',
    emptyTitle: 'Noch keine Einträge', emptyDesc: 'Lege den ersten Eintrag an oder importiere Daten.', newEntry: '＋ Neuer Eintrag',
    syncedBadge: '⟳ 3 Orte', syncedText: '<b>Unsere Mission:</b> Dem Arbeitstag echtes Gewicht nehmen – ruhig, klar, wirksam.',
    notes: '📝 Notizen', tasks: '✅ Aufgaben', files: '📎 Dateien', notesText: 'Freie Notizen zum Projekt – Protokolle, Ideen, Entwürfe.', tasksText: 'Aufgaben zu diesem Projekt, verknüpft mit der Datenbank.', filesText: 'Angehängte Dateien und Exporte.',
    week: 'Woche', month: 'Monat', quarter: 'Quartal', activePages: 'Aktive Seiten', aiRequests: 'KI-Anfragen', openTasks: 'Offene Aufgaben', deltaPages: '▲ 12 diese Woche', deltaAi: '▲ 23 %', deltaTasks: '▼ 5 seit gestern',
    people: '5 Personen haben Zugriff', weekPlan: 'Wochenplan einfügen', minutes: 'Meeting-Protokoll einfügen', retro: 'Retro-Board einfügen',
    modelPro: 'Mona Pro', modelProDesc: 'Am besten für lange Dokumente und Recherche.', modelFast: 'Mona Fast', modelFastDesc: 'Schnelle Antworten, geringere Kosten.', changePhoto: 'Foto ändern', remove: 'Entfernen',
    dangerTitle: 'Gefahrenzone', dangerDesc: 'Das Löschen des Workspace entfernt alle Seiten.', deleteWorkspace: 'Workspace löschen', editableHint: 'Hier steht Block-Inhalt – klicken zum Fokussieren.',
    mentionPerson: 'Sara Lindt', mentionPage: '📄 Onboarding', mentionDate: '📅 20. Mai',
    account: 'Konto', myProfile: 'Mein Profil', appearance: 'Darstellung', notifications: 'Benachrichtigungen', aiAssistant: 'KI-Assistent', general: 'Allgemein', members: 'Mitglieder',
    userName: 'Marcel Karas', userMail: 'marcel@monahilft.de', theme: 'Theme', light: 'Hell', dark: 'Dunkel', system: 'System', language: 'Sprache',
    rename: 'Umbenennen', duplicate: 'Duplizieren', moveTo: 'Verschieben nach …', page: 'Seite', options: 'Optionen', searchCommand: 'Suchen oder Befehl eingeben …',
    pages: 'Seiten', actions: 'Aktionen', newPageCmd: 'Neue Seite anlegen', toggleTheme: 'Theme wechseln', openSettings: 'Einstellungen öffnen', exportPage: 'Seite exportieren …',
    dbName: 'Name', dbStatus: 'Status', dbOwner: 'Verantwortlich', dbDue: 'Fällig', dbProgress: 'Fortschritt', table: '▦ Tabelle', board: '▤ Board',
    p1: 'App-Shell & Sidebar', p2: 'Seiten-Shell & Typografie', p3: 'Datenbank-Tabellenansicht', p4: 'Board-Ansicht & Drag-and-Drop', statusDone: 'Erledigt', statusProgress: 'In Arbeit', statusPlanned: 'Geplant',
    searchRows: 'Zeilen durchsuchen …', filterDone: 'Status: Erledigt', commentText1: 'Die Board-Ansicht fühlt sich schon sehr nah am Original an. 👍', commentText2: 'Ich habe die überfälligen Einträge markiert und eine Zusammenfassung vorbereitet.', commentPlaceholder: 'Kommentieren …', send: 'Senden',
    you: 'Du', aiName: 'Mona', aiBadge: '· KI', aiQuestion: 'Fasse die offenen Aufgaben dieses Projekts zusammen.', aiAnswer: 'Zwei Aufgaben sind offen: die <b>Tabellenansicht</b> steht bei 65 % (fällig 20. Mai), das <b>Board mit Drag-and-Drop</b> ist geplant.', copy: '📋 Kopieren', rephrase: '↻ Umformulieren', askAi: 'Frag Mona etwas …',
    toastText: 'Einstellungen gespeichert', showToast: 'Toast zeigen', openModal: 'Einstellungen öffnen', openPalette2: 'Palette öffnen (⌘K)', pickEmoji: 'Icon wählen', navigate: 'navigieren', openHint: 'öffnen', toggleHint: 'umschalten',
  },
};
